modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="dryingpan"
version="${file.jarVersion}"
displayURL="https://github.com/MerchantPug/drying-pan/"
credits="Brock"
authors="MerchantPug"
displayName="Drying Pan"
description='''
Hey I know! I'll use my trusty frying pan as a drying pan.
'''

[[dependencies.dryingpan]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dryingpan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
